= ansible-role-checkmk_server
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge
:no_change_needed: These variables do not need to be changed under normal circumstances, and certainly not if you are using the default version of the server.

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-checkmk_server/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-checkmk_server/actions/workflows/ci.yml/badge.svg[Testing CI]]

// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-checkmk_server/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-checkmk_server/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]
https://open.vscode.dev/JonasPammer/ansible-role-checkmk_server[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]


ifdef::env-github[]
[TIP]
__A single-page version of this README can be found at https://JonasPammer.github.io/ansible-role-checkmk_server[
JonasPammer.github.io/ansible-role-checkmk_server].__
endif::[]


An Ansible role for installing CheckMK RAW edition, setting up an initial site and configuring vital parameters of that site.

This role does *not*

* configure NTP (recommended by CheckMk)
* configure a SMTP-Server

toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.


The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

[source,yaml]
----
checkmk_site_url:
----
#Required.# URL resolving to the CheckMk site. Must not end with an `/`.

[source,yaml]
----
checkmk_server_site: "main"
----
Name of OMD "site" to create;
this is often shown as `my-site` in the CheckMK documentation examples.

[source,yaml]
----
checkmk_server_version: "2.0.0p17"
----
Version of CheckMK RAW edition to install


[[variables::installation]]
=== Role Variables used for installing
[source,yaml]
----
checkmk_server_prerequisites: [OS-specific by default, see /vars directory]
----
List of packages to install using the system's package manager.

Note that this role makes use of the
https://linuxhint.com/enable-powertools-repository-centos/[PowerTools]
repository if `dnf` is the system's package manager (as defined by `ansible_pkg_mgr`).

[source,yaml]
----
checkmk_server_install_cache_valid_time: "3600"
----
(Debian/Ubuntu only)
`cache_valid_time` passed to the `apt` module.

[source,yaml]
----
checkmk_server_download_package: [OS-specific by default, see /vars directory]
checkmk_server_download_checksum: [OS-specific by default, see /vars directory]
checkmk_server_download_url: "https://download.checkmk.com/checkmk/{{ checkmk_server_version }}/{{ checkmk_server_download_package }}"
checkmk_server_download_pubkey_url: "https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg"
checkmk_server_download_dest: "{{ checkmk_server_download_dest_folder }}/{{ checkmk_server_download_package }}"
checkmk_server_download_dest_folder: "/opt"
checkmk_server_download_mode: u=rw,g=r,o=r

checkmk_server_man_path: "/usr/share/man/man8"
checkmk_server_man_mode: u=rwx,g=rx,o=rx

checkmk_server_omd_setup_command: "omd setup"
checkmk_server_omd_setup_creates: "/opt/omd"
----
_{no_change_needed}_


[[variables::site]]
=== Role Variables used for site creation

[source,yaml]
----
checkmk_server_htpasswd: ~  # not defined by default
----
If not defined, CheckMk generates a random password and outputs it into `checkmk_server_omd_create_creates`.

[source,yaml]
----
checkmk_server_omd_create_command: "omd create {{ checkmk_server_site }}"
checkmk_server_omd_create_creates: "/opt/omd/sites/{{ checkmk_server_site }}"
checkmk_server_log_dest: "/opt/omd/sites/{{ checkmk_server_site }}/omd-create.log"
checkmk_server_log_group: "{{ checkmk_server_site }}"
checkmk_server_log_mode: 'u=rw,g=,o='
checkmk_server_log_owner: "{{ checkmk_server_site }}"

checkmk_server_htpasswd_group: "{{ checkmk_server_site }}"
checkmk_server_htpasswd_mode: u=rw,g=rw,o= # pragma: allowlist secret
checkmk_server_htpasswd_name: "cmkadmin" # pragma: allowlist secret
checkmk_server_htpasswd_owner: "{{ checkmk_server_site }}"
checkmk_server_htpasswd_path: "/opt/omd/sites/{{ checkmk_server_site }}/etc/htpasswd"

checkmk_server_omd_start_command: "omd start {{ checkmk_server_site }}"
checkmk_server_omd_start_creates: "/opt/omd/sites/{{ checkmk_server_site }}/tmp/apache/run/apache.pid"
----
_{no_change_needed}_


[[variables::component_config]]
=== Role Variables used to configure CheckMk's components

OMD is a system that integrates multiple software components into a monitoring system.
In so doing, some components are optional, and for some there are alternatives or different operational settings.
https://docs.checkmk.com/latest/en/omd_basics.html#omdconfig[All of this]
can be comfortably configured with these variables (actually issues `omd config`).

#Note that the CheckMk site must temporarily be stopped if a change is required.#

The most important are:

CORE::
Selection of the monitoring core.
MKEVENTD::
Activates the Checkmk Event Console, with which the syslog messages, SNMP-Traps and other events can be processed
MKNOTIFYD::
Enterprise Editions: Activates the notification spooler.
AUTOSTART::
This is primarily of interest for test installations that should not normally start by themselves.
LIVESTATUS_TCP::
Allows external access to the status data for this site.
A distributed monitoring can be constructed with this.
The status of this instance can be incorporated into the central instance.
Please only activate it in a secure network.


[source,yaml]
----
checkmk_server_site_conf: true
----
Enable/Disable configuration of site configuration by this role.

==== General

[source,yaml]
----
checkmk_server_site_conf_ADMIN_MAIL:
checkmk_server_site_conf_AUTOSTART: "on"
checkmk_server_site_conf_CORE: nagios
checkmk_server_site_conf_TMPFS: "on"
----

==== Web GUI

[source,yaml]
----
checkmk_server_site_conf_APACHE_MODE: own
checkmk_server_site_conf_APACHE_TCP_ADDR: 127.0.0.1
checkmk_server_site_conf_APACHE_TCP_PORT: 5000
checkmk_server_site_conf_MULTISITE_AUTHORISATION: "on"
checkmk_server_site_conf_MULTISITE_COOKIE_AUTH: "on"
checkmk_server_site_conf_NAGIOS_THEME: classicui
----

==== Addons
[source,yaml]
----
checkmk_server_site_conf_MKEVENTD: "on"
checkmk_server_site_conf_MKEVENTD_SNMPTRAP: "off"
checkmk_server_site_conf_MKEVENTD_SYSLOG: "off"
checkmk_server_site_conf_MKEVENTD_SYSLOG_TCP: "off"
checkmk_server_site_conf_PNP4NAGIOS: "on"
----

==== Distributed Monitoring
[source,yaml,subs="+quotes,macros"]
----
checkmk_server_site_conf_LIVESTATUS_TCP: "off"
checkmk_server_site_conf_NSCA: "off"
----


[[public_vars]]
== 📜 Facts/Variables defined by this role

Each variable listed in this section
is dynamically defined when executing this role (and can only be overwritten using `ansible.builtin.set_facts`) _and_
is meant to be used not just internally.


[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/default/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/default/prepare.yml[]
[source,yaml]
----
include::molecule/default/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_checkmk_server.svg[
requirements.yml dependency graph of jonaspammer.checkmk_server]
====

.Minimum Viable Play
====
[source,yaml]
----
roles:
  - "jonaspammer.checkmk_server"

vars:
  some_var: "some_value"
----
====


[[development]]
== 📝 Development
include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-checkmk_server/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-checkmk_server/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
