---
# tasks file of roles/checkmk

- name: get current value of site configuration variable {{ item.var }}
  ansible.builtin.command: "{{ checkmk_server_omd_config_show_command }}"
  register: _register
  changed_when: false

- when: _register.stdout != item.val | string
  block:
    - name: stop site if site configuration variable {{ item.var }} needs to be changed.
      ansible.builtin.command: "{{ checkmk_server_omd_stop_command }}"
      register: __register
      changed_when: "{{ checkmk_server_omd_stop_changed_when }}"

    - name: change value of site configuration variable {{ item.var }} (when different).
      ansible.builtin.command: "{{ checkmk_server_omd_config_set_command }}"
      changed_when: true
