---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all

  tasks:
    - name: Check http://localhost/master
      ansible.builtin.uri:
        url: "http://localhost/master"
        return_content: true
      register: this_verify
      failed_when: "'Checkmk Local site master' not in this_verify.content"
