---
name: Check for new CheckMK Version
"on":
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run in dry-run mode (Disable pushing changes and do not create any Issues/PRs)"
        required: true
        default: false
        type: boolean
  push:
    branches:
      - master
    paths:
      - ".github/workflows/check-new-version.yml"
      # as per __scripts/ci.py
      - "defaults/main.yml"
    tags:
      - "*"
  schedule:
    # At 05:00 on Sunday.
    - cron: "0 5 * * 0"

permissions:
  contents: read

jobs:
  check-new-version:
    name: Run __scripts/ci.py
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    permissions:
      contents: write

    steps:
      - name: check out the codebase
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: set up python 3
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
        with:
          python-version: "3.x"

      - name: setup git config
        run: |
          git config --global user.name 'Jonas Pammer'
          git config --global user.email 'opensource@jonaspammer.at'
          git remote -v

      - name: install python dependencies
        run: |
          python3 -m pip install -r __scripts/requirements.txt

      - name: Run ci.py
        id: script_output
        run: |
          python3 -m __scripts.ci -v ${{ '--dry-run' if github.event.inputs.lint == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_PAT }}
          AUTO_UPDATE_PAT: ${{ secrets.AUTO_UPDATE_PAT }}
          PY_COLORS: 1
